source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'

def shared_pods
    pod 'BitmovinComScoreAnalytics', path: '../'
    pod 'BitmovinPlayer', '2.51.0'
    pod 'SwiftLint'
    pod 'ComScore', '6.5.0'
end

target 'BitmovinComScoreAnalytics_Example' do
  use_frameworks!
  platform :ios, '9.0'
  shared_pods
  pod 'GoogleAds-IMA-iOS-SDK', '3.11.1'
end

target 'BitmovinComScoreAnalytics_Example_tvOS' do
    use_frameworks!
    platform :tvos, '9.0'
    shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "Updating #{target.name} BUILD_LIBRARY_FOR_DISTRIBUTION"
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
