def shared_pods
    pod 'BitmovinComScoreAnalytics', path: '../'
    pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.35.0'
    pod 'SwiftLint'
    pod 'ComScore', '5.8.7'
end

target 'BitmovinComScoreAnalytics_Example' do
  use_frameworks!
  platform :ios, '9.0'
  shared_pods
  pod 'GoogleAds-IMA-iOS-SDK', '3.7.0'
end

target 'BitmovinComScoreAnalytics_Example_tvOS' do
    use_frameworks!
    platform :tvos, '9.0'
    shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "Updating #{target.name} BUILD_LIBRARY_FOR_DISTRIBUTION"
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
